import type React from 'react';
import './sanctuary-sections.css';
const SIZE=1024;
const views=[{name:'Араг яс',en:'Skeleton',scale:1,note:'Гавал, нуруу, хавирга, мөчдийн байрлалыг ажиглаарай.'},{name:'Гавал & шүд',en:'Skull & teeth',scale:1.7,note:'Гавлын нүх, эрүү, шүдний хэлбэрийг ажиглаарай.'},{name:'Нуруу & хавирга',en:'Spine & ribs',scale:1.6,note:'Нурууны нугалам, хавирганы байрлал ба хэлбэрийг ажиглаарай.'}];
type Point={x:number;y:number};type Grain=Point&{vx:number;vy:number;life:number;size:number};
export function ExcavationLab({currentLang='mn',runtime}:{currentLang?:string;runtime:typeof React}){
 const mn=currentLang==='mn',canvas=runtime.useRef<HTMLCanvasElement>(null),dust=runtime.useRef<HTMLCanvasElement>(null),brush=runtime.useRef<HTMLDivElement>(null);
 const drawing=runtime.useRef(false),last=runtime.useRef<Point|null>(null),particles=runtime.useRef<Grain[]>([]),lastSample=runtime.useRef(0),keyboard=runtime.useRef(0);
 const [view,setView]=runtime.useState(0),[reset,setReset]=runtime.useState(0),[progress,setProgress]=runtime.useState(0),[tool,setTool]=runtime.useState<'soft'|'fine'>('soft');
 runtime.useEffect(()=>{const ctx=canvas.current?.getContext('2d',{willReadFrequently:true});if(!ctx)return;
  ctx.globalCompositeOperation='source-over';const data=ctx.createImageData(SIZE,SIZE);let seed=971;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
  for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const i=(y*SIZE+x)*4;const noise=(rand()-.5)*37;const undulation=Math.sin(x/32+y/53)*4+Math.sin(x/83-y/39)*5;const light=9*(1-y/SIZE);data.data[i]=190+noise+undulation+light;data.data[i+1]=159+noise*.85+undulation+light;data.data[i+2]=112+noise*.65+undulation+light;data.data[i+3]=255;}ctx.putImageData(data,0,0);
  for(let i=0;i<35000;i++){const x=rand()*SIZE,y=rand()*SIZE,r=.35+rand()*1.3;ctx.fillStyle=i%3?'rgba(86,62,37,.19)':'rgba(255,244,216,.55)';ctx.beginPath();ctx.ellipse(x,y,r,r*.6,-.4,0,Math.PI*2);ctx.fill();}
  for(let i=0;i<65;i++){const x=rand()*SIZE,y=rand()*SIZE,r=2+rand()*5;ctx.shadowColor='rgba(65,44,26,.3)';ctx.shadowBlur=2;ctx.shadowOffsetY=1.5;ctx.fillStyle=['#b89a70','#aa8d65','#d6bd95'][i%3];ctx.beginPath();ctx.ellipse(x,y,r,r*.6,rand()*3,0,Math.PI*2);ctx.fill();}ctx.shadowBlur=0;ctx.shadowOffsetY=0;
  drawing.current=false;last.current=null;particles.current=[];keyboard.current=0;setProgress(0);
 },[view,reset]);
 runtime.useEffect(()=>{let frame=0;let previous=0;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const animate=(now:number)=>{const ctx=dust.current?.getContext('2d');const step=Math.min(2,(now-previous)/16||1);previous=now;if(ctx){ctx.clearRect(0,0,SIZE,SIZE);particles.current=particles.current.filter(p=>p.life>0);for(const p of particles.current){p.x+=p.vx*step;p.y+=p.vy*step;p.vx*=.94;p.vy+=.035*step;p.life-=.035*step;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle='#e3c99e';ctx.shadowColor='#725332';ctx.shadowBlur=1;ctx.shadowOffsetY=1;ctx.fillRect(p.x,p.y,p.size,p.size*.7);}ctx.globalAlpha=1;}frame=requestAnimationFrame(animate);};if(!reduced)frame=requestAnimationFrame(animate);return()=>cancelAnimationFrame(frame);
 },[]);
 const sample=()=>{const ctx=canvas.current?.getContext('2d');if(!ctx)return;const d=ctx.getImageData(0,0,SIZE,SIZE).data;let remaining=0,total=0;for(let i=3;i<d.length;i+=128){remaining+=d[i]/255;total++;}setProgress(Math.round((1-remaining/total)*100));};
 const erase=(x:number,y:number)=>{const ctx=canvas.current?.getContext('2d');if(!ctx)return;const prev=last.current??{x,y};const dx=x-prev.x,dy=y-prev.y;const distance=Math.hypot(dx,dy);const r=tool==='soft'?30:13;const steps=Math.max(1,Math.ceil(distance/7));ctx.globalCompositeOperation='destination-out';
  for(let i=0;i<=steps;i++){const px=prev.x+dx*i/steps,py=prev.y+dy*i/steps;const gradient=ctx.createRadialGradient(px,py,0,px,py,r);gradient.addColorStop(0,'rgba(0,0,0,.24)');gradient.addColorStop(.45,'rgba(0,0,0,.12)');gradient.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=gradient;ctx.fillRect(px-r,py-r,r*2,r*2);}
  last.current={x,y};if(particles.current.length<200){for(let i=0;i<6;i++)particles.current.push({x:x+(Math.random()-.5)*r,y:y+(Math.random()-.5)*r,vx:dx*.04+(Math.random()-.5)*3,vy:dy*.04-1-Math.random()*2,life:.6+Math.random()*.3,size:.7+Math.random()*1.7});}
  if(performance.now()-lastSample.current>160){sample();lastSample.current=performance.now();}
 };
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const box=e.currentTarget.getBoundingClientRect();const x=(e.clientX-box.left)*SIZE/box.width,y=(e.clientY-box.top)*SIZE/box.height;if(brush.current){brush.current.style.left=`${x/SIZE*100}%`;brush.current.style.top=`${y/SIZE*100}%`;brush.current.style.opacity='1';brush.current.style.transform=`translate(-28%, -72%) rotate(${drawing.current?-25:-15}deg)`;}if(drawing.current)erase(x,y);};
 const stop=()=>{drawing.current=false;last.current=null;sample();};
 return <section id="fossil-lab" className="sanctuary-lab"><header><span className="sanctuary-eyebrow">INTERACTIVE PALEONTOLOGY · {mn?'СУРГАЛТЫН СИМУЛЯЦИ':'EDUCATIONAL SIMULATION'}</span><h2>{mn?'Элсний цаана нуугдсан ертөнц.':'A world beneath the sand.'}</h2><p>{mn?'Багсаа зөөлөн чирж, элсийг бага багаар зайлуулаарай. Нэг газраа давтан багсдах тусам олдвор тодорно.':'Gently sweep the brush. Repeated passes reveal the fossil beneath.'}</p></header>
 <div className="sanctuary-lab-grid"><div className="sanctuary-dig-card"><div className="sanctuary-tool-row"><div>{(['soft','fine'] as const).map(t=><button key={t} aria-pressed={tool===t} onClick={()=>setTool(t)}>{t==='soft'?(mn?'Зөөлөн багс':'Soft brush'):(mn?'Нарийн багс':'Fine brush')}</button>)}</div><button onClick={()=>setReset(v=>v+1)}>{mn?'Дахин эхлэх':'Reset'}</button></div>
 <div className="sanctuary-dig-surface sanctuary-real-dig"><img className={`sanctuary-fossil-photo fossil-view-${view}`} src="./fossil-excavation-v2.jpg" alt={mn?'AI-аар үүсгэсэн сургалтын араг ясны дүрслэл':'AI-generated educational fossil reconstruction'} style={{transform:`scale(${views[view].scale})`}}/><canvas ref={canvas} width={SIZE} height={SIZE} tabIndex={0} role="button" aria-label={mn?'Элс арилгах. Чирэх эсвэл Enter дарна уу.':'Brush sand: drag or press Enter.'} onPointerDown={e=>{drawing.current=true;last.current=null;e.currentTarget.setPointerCapture(e.pointerId);point(e);}} onPointerMove={point} onPointerUp={stop} onPointerCancel={stop} onLostPointerCapture={stop} onPointerLeave={()=>{if(!drawing.current&&brush.current)brush.current.style.opacity='0';}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();const n=keyboard.current++%625,x=20+(n%25)*41,y=20+Math.floor(n/25)*41;last.current=null;for(let i=0;i<8;i++)erase(x,y);sample();}}}/><canvas ref={dust} width={SIZE} height={SIZE} className="sanctuary-dust" aria-hidden="true"/>
 <div ref={brush} className={`sanctuary-brush brush-${tool}`} aria-hidden="true"><svg viewBox="0 0 100 230"><defs><linearGradient id="brushWood" x2="1" y2="0"><stop stopColor="#503320"/><stop offset=".35" stopColor="#c69053"/><stop offset=".65" stopColor="#e0b16d"/><stop offset="1" stopColor="#684326"/></linearGradient><linearGradient id="brushMetal" x2="1" y2="0"><stop stopColor="#7b7469"/><stop offset=".4" stopColor="#f1e7cb"/><stop offset=".6" stopColor="#b9b2a2"/><stop offset="1" stopColor="#716b5f"/></linearGradient></defs><path d="M44 12 Q50 3 57 12 L65 138 L35 138 Z" fill="url(#brushWood)" stroke="#654328"/><path d="M35 131 L65 131 L70 166 L30 166 Z" fill="url(#brushMetal)" stroke="#6b665b"/><path d="M30 165 L70 165 L80 213 Q50 225 20 213 Z" fill="#bea272"/>{Array.from({length:27},(_,i)=><path key={i} d={`M${31+i*1.4} 165 Q${28+i*1.7} 190 ${21+i*2.2} ${210+Math.sin(i*1.7)*6}`} stroke={i%3?'#7e6240':'#e6cf9d'} strokeWidth="1" fill="none"/>)}</svg></div>
 {progress>=80&&<span className="sanctuary-discovered">✓ {mn?'Олдвор илэрлээ':'Discovery complete'}</span>}</div><div className="sanctuary-progress-row"><span>{mn?'Цэвэрлэсэн талбай':'Surface cleared'}</span><strong aria-live="polite">{progress}%</strong></div><progress value={progress} max="100" aria-label="Excavation progress"/>
 </div><aside className="sanctuary-find-card"><span className="sanctuary-eyebrow">{mn?'ОЛДВОРЫН ТЭМДЭГЛЭЛ':'FIELD NOTES'}</span><h3>{mn?views[view].name:views[view].en}</h3><p>{mn?views[view].note:'Observe the shape and arrangement of the bones.'}</p><div className="sanctuary-learning-note">{mn?'Зөөлөн багс өргөн талбайг цэвэрлэнэ. Нарийн багс ясны орчимд болгоомжтой ажиллахад тохиромжтой.':'Use the soft brush for broad areas and the fine brush around delicate details.'}</div><h4>{mn?'Судлах хэсэг':'Explore a detail'}</h4><div className="sanctuary-find-tabs">{views.map((v,i)=><button key={v.en} aria-pressed={view===i} onClick={()=>setView(i)}>{mn?v.name:v.en}</button>)}</div><p className="sanctuary-small">{mn?'AI-аар үүсгэсэн сургалтын дүрслэл. Бодит музейн олдворын зураг биш.':'AI-generated educational illustration, not a photograph of a real specimen.'}</p><p className="sanctuary-small">{mn?'Бодит олдворыг хөдөлгөхгүй, байршлыг тэмдэглэж мэргэжлийн байгууллагад мэдэгдээрэй.':'Do not disturb a real fossil; record its location and contact specialists.'}</p></aside></div></section>;
}

