export function conciergeReply(query: string, lang = 'mn'): string {
  const q=query.toLowerCase().normalize('NFKC');const mn=lang==='mn';
  const has=(words:string[])=>words.some(w=>q.includes(w));
  if(has(['захиал','zahial','zahioal','reserve','booking','book','예약','预订','予約','брони','reserv'])) return mn?'Өрөө захиалахын тулд “Захиалга” хэсэгт ирэх, буцах огноо, өрөөний төрөл, зочдын тоо болон холбоо барих мэдээллээ бөглөөрэй. Хүсэлт bataartravel@gmail.com руу илгээгдэнэ. Бааз хариу өгсний дараа захиалга баталгаажна.':'Open the reservation tab and enter your dates, room, guests and contact details. Requests go to bataartravel@gmail.com. The camp must confirm availability before your booking is confirmed.';
  if(has(['имэйл','мэйл','mail','утас','utas','holboo','холбоо','contact','phone','연락','电话','連絡'])) return mn?'Бидэнтэй bataartravel@gmail.com, +976 7201 0099 эсвэл +976 8822 3584 дугаараар холбогдоорой.':'Contact the camp at bataartravel@gmail.com, +976 7201 0099 or +976 8822 3584.';
  if(has(['үнэ','une','өрөө','uruu','room','rate','price','가격','房','preis','tarif','料金'])) return mn?'Люкс, стандарт болон гэр бүлийн өрөөний сонголттой. Гэр бүлийн өрөө нь том давхар ортой мастер өрөө, хувийн шүршүүр болон ариун цэврийн өрөөтэй. Үнэ, сул өрөөг сонгосон огноо, зочдын тоогоор баазаас баталгаажуулна. “Захиалга” хэсгээс хүсэлтээ илгээгээрэй.':'Choose Deluxe, Standard or Family Suite. The family suite has a double-bed master bedroom and private bathroom. Ask the camp to confirm rates and availability for your dates and guest count.';
  if(has(['зам','чиглэл','хаана','байрш','zam','haana','route','location','transfer','pickup','4x4','달란','路线','アクセス'])) return mn?'Бааз Өмнөговь аймгийн Гурвантэс сум, Тост Тосонбумбын нурууны бүсэд байрладаг. Даланзадгадаас очих зам, 4x4 тосох үйлчилгээг баазтай урьдчилан тохироорой: +976 7201 0099.':'The camp is in Gurvantes, South Gobi, near Tost Tosonbumba. Arrange your route and 4x4 transfer from Dalanzadgad with the camp in advance: +976 7201 0099.';
  if(has(['starlink','wifi','wi-fi','интернэт','нарны','цахилгаан','solar','internet','эрчим','시설'])) return mn?'Бааз Starlink интернэт, нарны цахилгаан болон халуун шүршүүртэй. Таны ирэх хугацаанд хэрэгтэй тусгай үйлчилгээний бэлэн байдлыг баазтай урьдчилан баталгаажуулаарай.':'The camp offers Starlink internet, solar power and hot showers. Confirm any specific requirements with the camp before arrival.';
  if(has(['аялал','ayal','ирвэс','irves','цав','khermen','dino','fossil','tour','expedition','leopard','공룡','恐龙'])) return mn?'Тост Тосонбумба, Хүрэн ханын хэц, Хэрмэн цавын чиглэлийн аяллуудтай. Хүссэн чиглэл, огноо, хүний тоогоо хэлбэл захиалгын хүсэлтдээ оруулахад тусална. Ирвэс харах нь байгалийн нөхцөлөөс хамаардаг.':'Explore Tost Tosonbumba, Khuren Khan or Khermen Tsav. Include your preferred route, dates and party size in the reservation request. Wildlife sightings depend on natural conditions.';
  if(has(['сайн','sain','hello','hi','안녕','你好','こんにちは'])) return mn?'Сайн байна уу! Өрөө, захиалга, зам чиглэл, аялал, үйлчилгээний талаар асуугаарай. Танд ямар мэдээлэл хэрэгтэй вэ?':'Welcome! Ask about rooms, reservations, directions, tours or camp facilities.';
  return mn?'Энэ асуултын баталгаатай мэдээлэл лавлахад алга. Илүү тодруулж бичих эсвэл bataartravel@gmail.com / +976 7201 0099 дугаараар баазтай холбогдоорой.':'I do not have verified information for that question. Please clarify or contact bataartravel@gmail.com / +976 7201 0099.';
}
